const trending = [
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABVoUb_b5kh_yNaUP7KrJ0SixY7wboYlzRCUdKII9nZ7oSYyAYPShAtL0spCP-KQXAvTngiRZqy7Kqk0egCiKWfpaIrc4S9LT9gPeEcdFpM3H9CuyLTNXW-nev14zWvjHmDzP.jpg?r=cac',
        alt: 'Midnight Diner: Tokyo Stories',
        maturityRating: '13+',
        seasonLength: '3 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Sentimental', 'Understated', 'Drama'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdgTW1x53wm762Jk0TtkGTOhi4boVORa2qQg-GvNlkbeu_Cg5xSrsHN0aE-03y_bkmQwnxnvFwlsuDbabRnWUgAk0KkyOLoE_f8.webp?r=a65',
        alt: 'Lost',
        maturityRating: '16+',
        seasonLength: '6 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Emotional', 'Exciting', 'Adventure'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABX2PfVhkMZlw8pvS-LUgyk8GpmKv48_tRsA6rgSV8ppFvijet4MWICbJW-3I369_O1kaxVEl0aCY957Ma9wpLzqm37MYsN5AQT8.webp?r=cfb',
        alt: 'Adventure Time',
        maturityRating: '10+',
        seasonLength: '4 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Clever', 'Quirky', 'Kids'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQOGyZS-6Oi0JRI__YiHy2cDTTktNLJ4hL0_EiSiKvh0mQPhpPNqnUo6a8SNzwFRnZHgn_4D19cLS5DhSqZnkxQ5AjI4M8elvdM.webp?r=f29',
        alt: 'Avatar',
        maturityRating: '10+',
        seasonLength: '3 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Clever', 'Rousing', 'Imaginative'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQ7JWJm3TNKnhWZwFkZg5MwlCJoWXNedXpecv1qdsym10FF3x7rMPxOqcvFeMIe4m-e0Lpz0M_78zcFfp2NX4JD_E6ad_SF6KLw.webp?r=82d',
        alt: 'The Office',
        maturityRating: '13+',
        seasonLength: '9 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Witty', 'Irreverent', 'Sitcoms'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABeMSDWszjl16jq7qFSWk8uIzw0T53Vaag65yKbuXMN-etObAVJPWHbdvx8oe0Kv362vFmLe7KX0iL4Vb3eAPAUTit1ueVdBY3ZILFKNIf4RAKTLx8jgRNHokWBKgiIiTv1hF.jpg?r=696',
        alt: 'Better Call Saul',
        maturityRating: '16+',
        seasonLength: '6 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Offbeat', 'Gritty', 'TV Dramas'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfw8DaShSWvrVPjNRyQZMNXg4_CVerMtfpZHCUspl1T5KTO-rVUxu_rQVr6W_Y7BDIuWljsPzXXZqz7IeC-XwCFHu3bKN6ZUtp8.webp?r=af6',
        alt: 'Old Enough!',
        maturityRating: '7+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Feel-good', 'Familty Time TV', 'Japanese'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfJTX7eAb5oFLjM9kuUUEskoHC8dP-kQOLCu1Iq85xFEu_AehlXpQbEhtb5N9KFE1bW7HzNDCS3Z-h0Qm6RtVuWWd-gUqenlYfl4bP5UZD0rD39m1U_Y-2GqbKFmNZfw5BoG.jpg?r=72f',
        alt: "JoJo's Bizarre Adventure",
        maturityRating: '16+',
        seasonLength: '5 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Exciting', 'Shounen Anime', 'Action Anime'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABWc2d5lqwRHzflRJSjpRzQCrHOSqLYzJ2Ka519EwDMpWe1oaVaY__i_Onhz-z412wtPJRnPF38cf0O7KZhVWmmpJ1WuttbUWReOJ-6KUhfK70FyCUKxFFh_5-2SIZ-Cykr9l.jpg?r=1f3',
        alt: 'Our Universe',
        maturityRating: '7+',
        seasonLength: 'Limited Series',
        playerFeatureBadge: 'HD',
        genres: ['Relaxing', 'Cerebral', 'Family Time TV'],
    },
];

const watchAgain = [
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABZGjw3eiZBPX3PClNvoEW5Qvyuvg0yJ8WC1R00mYeeSrP_Wq1ObH3c9832gtAV4HbsH8Rktv0fA73AVOyQmTY6Gdm-AsJDqh7nMqvG2WABBh9agqH7mOoIgrmBD-pkWelBnN.jpg?r=962',
        alt: 'Live to 100: Secrets of the Blue Zones',
        maturityRating: '10+',
        seasonLength: 'Limited Series',
        playerFeatureBadge: 'HD',
        genres: ['Inspiring', 'Heartfelt', 'Food &amp; Travel TV'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABWFivdM01yCAxgcgMEukBOTzCCtQ02-SC9wLTAIqJOiJPOxsiuVnNokzw6ERYSLQ1s-NKqFXxyuU-WoIYQhG6w2Y_nuQ_d_A55n02xzfSVm5DJhN93-B5yg2RQEIaDp9cuqn.jpg?r=c49',
        alt: 'Unknown: Cosmic Time Machine',
        maturityRating: 'ALL',
        seasonLength: '1h 4m',
        playerFeatureBadge: 'HD',
        genres: [
            'Investigative',
            'Documentary Films',
            'Science &amp; Nature Docs',
        ],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdooux6TG8BM4ZrfzBAdgS6Uu7U3WZQt1Yql4STgFuz5q-yxiT_zasNUA1yzVy-40r57TGHRtSnrAWVEXJKzWKwyS7tKyPYI9aKDPcDFAZt1eGAeTY-WZdxiL3rrhjPFIKwl.jpg?r=ea6',
        alt: 'The Way of the Househusband',
        maturityRating: '13+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Deadpan', 'Absurd', 'Quirky'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABScU9si84a7dUBrLejJ56w8wBjDyedjmr2aoZwyuhkTFVioYvvC4B_3CDzXHO8bRil3zTFfoZe8OzJcU9RdIKTDdek0WWHhNzBO7k2ekpqmbUFXHADBlvGyuoj6B-EH0ORzG.jpg?r=112',
        alt: 'Mindhunter',
        maturityRating: '16+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Chilling', 'Psychological', 'TV Dramas'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABf2hzn0yZQQYIIfUgIbBPaN46wFbffcX1ZOhtq0q3e0-N_gLGH8Lx3s5DOmYls4PNHAKA1XP9BuwUIXOMrPyciiCrBwj3olikoI.webp?r=a41',
        alt: 'Interstellar',
        maturityRating: '13+',
        seasonLength: '2h 49m',
        playerFeatureBadge: 'HD',
        genres: ['Mind-Bending', 'Cerebral', 'Sci-Fi Movies'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABa5BCf6HoCBQCEQW5JNP301dwSPyJPEXbFicrHodTtnqA1AtzHfQyEfkHWQurDLPdc9Eq4LszcOs9gzzykJ3FvNwjhX2B7KLteY.webp?r=edf',
        alt: 'Rick and Morty',
        maturityRating: '16+',
        seasonLength: '7 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Absurd', 'Violent', 'Quirky'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABTzIxLs3nhQuvkJ10Bwvf9HcidFA1o9QcLrqrtqQ1kJsf5AsqxGJfrk1rLNymppxwozwev2aLGoYZyEKS3XpmOoZAv5oKcKSaHQ.webp?r=2b9',
        alt: 'Cowboy Bebop',
        maturityRating: '16+',
        seasonLength: '26 Episodes',
        playerFeatureBadge: 'HD',
        genres: ['Offbeat', 'Witty', 'Action Anime'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaE6ehOFF1Lgn84imWJtALvvF7ygfKVLE5Z2vn6Fq0_r16_PFpQgC62Vvxnx1g9GZ__OFtGlNLZsu4VbVmNfWRnbte2UE2GVMFV3zm0fZVvQuvD7RWr2ajUIQqmK5cPnE2NC.jpg?r=2b0',
        alt: 'The Wonderful Story of Henry Sugar',
        maturityRating: 'ALL',
        seasonLength: '39m',
        playerFeatureBadge: 'HD',
        genres: ['Imaginative', 'Dram Movies', 'Movies Based on Books'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfjGlvVeALl76ib7TIZy_-U7wyBKIldVloODtBfoHdKNe9Stp2FWnyciNYHa3XUuyZF_NN-JILrfNbSDya7qk_emCvgj0-OJlps.webp?r=b00',
        alt: 'Akira',
        maturityRating: '16+',
        seasonLength: '2h 4m',
        playerFeatureBadge: 'HD',
        genres: ['Exciting', 'Action Anime', 'Sci-Fi Movies'],
    },
];

const newReleases = [
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABT2Qef838XVZfk9dEVlOPc_DiEQdz9dv1VFqQUax22r97Vmp3vbaFbV917U31vkSAlyo4XLSdV0tN58NZh8j7xAJkhZwEVodoCM.webp?r=869',
        alt: "Frieren: Beyond Journey's End",
        maturityRating: '16+',
        seasonLength: '28 Episodes',
        playerFeatureBadge: 'HD',
        genres: ['Clever', 'Shounen Anime', 'Action Anime'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABVKG6dv0TLmYBjbfsd4VyWcgDUWK6hTbz5zlFzSdc6ybZtW8TAdlU1m8-gLrz91C2lbLorAyAzHPZgUUe99ZS_hn4sFu9BMWGJk5dO6BO4B5xBs8i9zQ4LFvP23-dfDfxHo7t2GNPPL0XOwk0OjAJvPe-aCv_E-72JPtd2hBUtaEPTIzd4aSsN8dqGyy2gHm376kzeMEzyq53d-GOCRjxPeUCTptKLO6eF6dxDCwKZrMZ2_MubgiI6_XhY5Wc44HYrvOqkYSJ5Sfa5cc8pb415s.webp?r=62b',
        alt: 'Resident Alien',
        maturityRating: '16+',
        seasonLength: '2 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Witty', 'Quirky', 'Imaginative'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaPTCx1yLWu1sbXcAxruWTjUrK1Su0DTixgAnFtKeLsQdRuuGZNCa42X6linq5D9k0knbFyUPh4Kx7vbAE4AO06tF3U17g2q4o0.webp?r=f8a',
        alt: 'Spider-Man: Across The Spider-Verse',
        maturityRating: '10+',
        seasonLength: '2h 21m',
        playerFeatureBadge: 'HD',
        genres: ['Adrenaline Rush', 'Imaginative', 'Exciting'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABY1vrZlJNXYxqXJGX9W7kRS_VKHtoqYmgj0xDbc640yxYJ6o2AqZ43_VLLbWpw04QHLrBunG-jj0K1vAut0uOdNDqW9vxc-dHTo.webp?r=118',
        alt: 'Mission Impossible: Dead Reckoning',
        maturityRating: '13+',
        seasonLength: '2h 44m',
        playerFeatureBadge: 'HD',
        genres: ['Witty', 'Suspensful', 'Spy Movies'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABZkkWNkGAs5fgRhpeAUXLE2RqFD_cow9RlWgnHfxvP5qXDuu0Mj6Cr466URUAFZO2xNwGOa-kufAcXzK25E1K3r8aOHH1mAAjrFFfbkBz1c1dakU9g-h4NHpRsiss3imrS1a8shAdmfp0kByRNEupfyvn2AajeWGLWwXGHX02TsYk5eTUuWT3OTxlbkkJF4.jpg?r=65d',
        alt: 'Zero Day',
        maturityRating: '16+',
        seasonLength: 'Limited Series',
        playerFeatureBadge: 'HD',
        genres: ['Psychological', 'Suspensful', 'Political TV Shows'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcgKBKBGERKlj6QsMIWWD4KRqFCtffAchnMg_Wwe4R5dFlSjb6T-rV2XSCqsu7rQEnqbtsQ6EBRmsEA4eJhmXJWJpMv7ZbpMOi4jPVY75z23C11vGlrOgbpX5ifTCB4FxhJOSOMfLY1H3OEIWCnh_cQ25lfGFjG-hZmY5gndF9U0zzbTKCR5uMj_d4UcE-0.jpg?r=aac',
        alt: 'Demon City',
        maturityRating: '16+',
        seasonLength: '1h 47m',
        playerFeatureBadge: 'HD',
        genres: ['Adrenaline Rush', 'Violent', 'Dark'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABbba4g2YCjdrB3rf9K38lCGa6UGO4zs721vYppWNzegToVjM1AWITFP_Rz9rlBLpn7j3KD0_j_h_fQxGkE6gPvpr2bejNFqD4XXQCUCaKgiMzNmEmItHIZE8wtaLTXpAepCu.jpg?r=ed4',
        alt: 'The Witcher: Sirens of the Deep',
        maturityRating: '16+',
        seasonLength: '1h 31m',
        playerFeatureBadge: 'HD',
        genres: ['Rousing', 'Imaginative', 'Dark'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABSl_Fp4vnvqvH2ABZwklOJzNGHzPdUHl8jAB26_Ov3dhcWzO7GUnrnAaGltXxJYb7e8J7985w0iIrHcnPbN0CsXdDPjgn0AM9FG1RYWXHNA2rHGeMLpWza6a1EiX7djOJTnANNNitM4KuXskF-jBRodxVMcCvd0vUjTWgIyMhxoc1U-ZuggvFnCQ6QXASNW0fYu7jqr7f_bg04LOpGEc3rLuqc5xW7liHUI5_lT30abtuEFZaa3y1Pncu37QKY0q8yZ74z7gpm4OiEsndxkOd1Rv.webp?r=3b7',
        alt: 'City Hunter',
        maturityRating: '13+',
        seasonLength: '4 Seasons',
        playerFeatureBadge: 'HD',
        genres: ['Raunchy', 'Exciting', 'Action Anime'],
    },
    {
        img: 'https://occ-0-6212-778.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUeCQchplAK-sETwkkHYiaspG0Z52N7x0jP4vzcnsjfBrKMXdrHjWkaU1rrOxR3qotLQboTa8oxLJQk8vaBG6r9aLqIlX_K22jo.webp?r=ba6',
        alt: 'Escape From Alcatraz',
        maturityRating: '13+',
        seasonLength: '1h 52m',
        playerFeatureBadge: 'HD',
        genres: ['Understated', 'Dark', 'Suspensful'],
    },
];
